server:
  port: 8001
spring:
  application:
    name: service-broken
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://110.41.12.241:3306/broken_price?useSSL=false
    username: root
    password: Cqupt@1234
    max-active: 200
    max-idle: 50
    min-idle: 5
    validation-query: SELECT 1
    validation-interval: 1000
    connection-test-query: SELECT 1
    connection-test-timeout: 5000
    max-lifetime: 300000
    idle-timeout: 300000
    maximum-pool-size: 100
  rabbitmq:
    host: 124.220.100.127
    port: 5563
    username: interviewer
    password: 666999
    virtual-host: brokenpricenode
    listener:
      simple:
        acknowledge-mode: manual

  data:
    redis:
      password: ofXz0NQxpJhd4P
      host: 124.223.162.132
      port: 6379
      database: 0
      timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          #最大阻塞等待时间(负数表示没限制)
          max-idle: 5
          min-idle: 0
mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lyu.broken.pojo.vo
  #扫描mapper文件
  mapper-locations: classpath:mappers/*.xml

my:
  exchangeName: exchange.delay
  queueNormalName: queue.delay.normal
